iranyitoszam = input('Írd be az irányítószámod: ')
varos = input('Írd be a közterület nevét: ')
jelleg = input('Írd be a közterület jellegét: ')
szam = input('Írd be a házszámodat: ')
print(f'A te címed: {iranyitoszam} {varos} {jelleg} {szam}')
r = input('Igaz ez?: ').lower()
if r == ('igen'): print('Akkor jó')
elif r == ('nem'): print('Akkor Bocs')
else: print('Milyen válasz ez te')